apiVersion: v1
kind: Pod
metadata:
  annotations:
    checksum/config: 5bff737798c08a9e75bb79a228410b88db8126aaa2eefb18fb1744f869295dcb
  creationTimestamp: "2022-11-03T04:06:48Z"
  generateName: cd-jenkins-
  labels:
    app.kubernetes.io/component: jenkins-controller
    app.kubernetes.io/instance: cd-jenkins
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: jenkins
    controller-revision-hash: cd-jenkins-86867ff66d
    statefulset.kubernetes.io/pod-name: cd-jenkins-0
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:checksum/config: {}
        f:generateName: {}
        f:labels:
          .: {}
          f:app.kubernetes.io/component: {}
          f:app.kubernetes.io/instance: {}
          f:app.kubernetes.io/managed-by: {}
          f:app.kubernetes.io/name: {}
          f:controller-revision-hash: {}
          f:statefulset.kubernetes.io/pod-name: {}
        f:ownerReferences:
          .: {}
          k:{"uid":"652da506-3127-4dc0-ab65-5e2a83dbdf3f"}: {}
      f:spec:
        f:containers:
          k:{"name":"config-reload"}:
            .: {}
            f:env:
              .: {}
              k:{"name":"FOLDER"}:
                .: {}
                f:name: {}
                f:value: {}
              k:{"name":"LABEL"}:
                .: {}
                f:name: {}
                f:value: {}
              k:{"name":"NAMESPACE"}:
                .: {}
                f:name: {}
                f:value: {}
              k:{"name":"POD_NAME"}:
                .: {}
                f:name: {}
                f:valueFrom:
                  .: {}
                  f:fieldRef: {}
              k:{"name":"REQ_METHOD"}:
                .: {}
                f:name: {}
                f:value: {}
              k:{"name":"REQ_RETRY_CONNECT"}:
                .: {}
                f:name: {}
                f:value: {}
              k:{"name":"REQ_URL"}:
                .: {}
                f:name: {}
                f:value: {}
            f:image: {}
            f:imagePullPolicy: {}
            f:name: {}
            f:resources: {}
            f:securityContext:
              .: {}
              f:allowPrivilegeEscalation: {}
              f:readOnlyRootFilesystem: {}
            f:terminationMessagePath: {}
            f:terminationMessagePolicy: {}
            f:volumeMounts:
              .: {}
              k:{"mountPath":"/var/jenkins_home"}:
                .: {}
                f:mountPath: {}
                f:name: {}
              k:{"mountPath":"/var/jenkins_home/casc_configs"}:
                .: {}
                f:mountPath: {}
                f:name: {}
          k:{"name":"jenkins"}:
            .: {}
            f:args: {}
            f:env:
              .: {}
              k:{"name":"CASC_JENKINS_CONFIG"}:
                .: {}
                f:name: {}
                f:value: {}
              k:{"name":"JAVA_OPTS"}:
                .: {}
                f:name: {}
                f:value: {}
              k:{"name":"JENKINS_OPTS"}:
                .: {}
                f:name: {}
                f:value: {}
              k:{"name":"JENKINS_SLAVE_AGENT_PORT"}:
                .: {}
                f:name: {}
                f:value: {}
              k:{"name":"POD_NAME"}:
                .: {}
                f:name: {}
                f:valueFrom:
                  .: {}
                  f:fieldRef: {}
              k:{"name":"SECRETS"}:
                .: {}
                f:name: {}
                f:value: {}
            f:image: {}
            f:imagePullPolicy: {}
            f:livenessProbe:
              .: {}
              f:failureThreshold: {}
              f:httpGet:
                .: {}
                f:path: {}
                f:port: {}
                f:scheme: {}
              f:periodSeconds: {}
              f:successThreshold: {}
              f:timeoutSeconds: {}
            f:name: {}
            f:ports:
              .: {}
              k:{"containerPort":8080,"protocol":"TCP"}:
                .: {}
                f:containerPort: {}
                f:name: {}
                f:protocol: {}
              k:{"containerPort":50000,"protocol":"TCP"}:
                .: {}
                f:containerPort: {}
                f:name: {}
                f:protocol: {}
            f:readinessProbe:
              .: {}
              f:failureThreshold: {}
              f:httpGet:
                .: {}
                f:path: {}
                f:port: {}
                f:scheme: {}
              f:periodSeconds: {}
              f:successThreshold: {}
              f:timeoutSeconds: {}
            f:resources:
              .: {}
              f:limits:
                .: {}
                f:cpu: {}
                f:memory: {}
              f:requests:
                .: {}
                f:cpu: {}
                f:memory: {}
            f:securityContext:
              .: {}
              f:allowPrivilegeEscalation: {}
              f:readOnlyRootFilesystem: {}
              f:runAsGroup: {}
              f:runAsUser: {}
            f:startupProbe:
              .: {}
              f:failureThreshold: {}
              f:httpGet:
                .: {}
                f:path: {}
                f:port: {}
                f:scheme: {}
              f:periodSeconds: {}
              f:successThreshold: {}
              f:timeoutSeconds: {}
            f:terminationMessagePath: {}
            f:terminationMessagePolicy: {}
            f:volumeMounts:
              .: {}
              k:{"mountPath":"/run/secrets/additional"}:
                .: {}
                f:mountPath: {}
                f:name: {}
                f:readOnly: {}
              k:{"mountPath":"/tmp"}:
                .: {}
                f:mountPath: {}
                f:name: {}
              k:{"mountPath":"/usr/share/jenkins/ref/plugins/"}:
                .: {}
                f:mountPath: {}
                f:name: {}
              k:{"mountPath":"/var/jenkins_cache"}:
                .: {}
                f:mountPath: {}
                f:name: {}
              k:{"mountPath":"/var/jenkins_config"}:
                .: {}
                f:mountPath: {}
                f:name: {}
                f:readOnly: {}
              k:{"mountPath":"/var/jenkins_home"}:
                .: {}
                f:mountPath: {}
                f:name: {}
              k:{"mountPath":"/var/jenkins_home/casc_configs"}:
                .: {}
                f:mountPath: {}
                f:name: {}
        f:dnsPolicy: {}
        f:enableServiceLinks: {}
        f:hostname: {}
        f:initContainers:
          .: {}
          k:{"name":"init"}:
            .: {}
            f:command: {}
            f:image: {}
            f:imagePullPolicy: {}
            f:name: {}
            f:resources:
              .: {}
              f:limits:
                .: {}
                f:cpu: {}
                f:memory: {}
              f:requests:
                .: {}
                f:cpu: {}
                f:memory: {}
            f:securityContext:
              .: {}
              f:allowPrivilegeEscalation: {}
              f:readOnlyRootFilesystem: {}
              f:runAsGroup: {}
              f:runAsUser: {}
            f:terminationMessagePath: {}
            f:terminationMessagePolicy: {}
            f:volumeMounts:
              .: {}
              k:{"mountPath":"/tmp"}:
                .: {}
                f:mountPath: {}
                f:name: {}
              k:{"mountPath":"/usr/share/jenkins/ref/plugins"}:
                .: {}
                f:mountPath: {}
                f:name: {}
              k:{"mountPath":"/var/jenkins_config"}:
                .: {}
                f:mountPath: {}
                f:name: {}
              k:{"mountPath":"/var/jenkins_home"}:
                .: {}
                f:mountPath: {}
                f:name: {}
              k:{"mountPath":"/var/jenkins_plugins"}:
                .: {}
                f:mountPath: {}
                f:name: {}
        f:restartPolicy: {}
        f:schedulerName: {}
        f:securityContext:
          .: {}
          f:fsGroup: {}
          f:runAsNonRoot: {}
          f:runAsUser: {}
        f:serviceAccount: {}
        f:serviceAccountName: {}
        f:subdomain: {}
        f:terminationGracePeriodSeconds: {}
        f:volumes:
          .: {}
          k:{"name":"jenkins-cache"}:
            .: {}
            f:emptyDir: {}
            f:name: {}
          k:{"name":"jenkins-config"}:
            .: {}
            f:configMap:
              .: {}
              f:defaultMode: {}
              f:name: {}
            f:name: {}
          k:{"name":"jenkins-home"}:
            .: {}
            f:name: {}
            f:persistentVolumeClaim:
              .: {}
              f:claimName: {}
          k:{"name":"jenkins-secrets"}:
            .: {}
            f:name: {}
            f:projected:
              .: {}
              f:defaultMode: {}
              f:sources: {}
          k:{"name":"plugin-dir"}:
            .: {}
            f:emptyDir: {}
            f:name: {}
          k:{"name":"plugins"}:
            .: {}
            f:emptyDir: {}
            f:name: {}
          k:{"name":"sc-config-volume"}:
            .: {}
            f:emptyDir: {}
            f:name: {}
          k:{"name":"tmp-volume"}:
            .: {}
            f:emptyDir: {}
            f:name: {}
    manager: kube-controller-manager
    operation: Update
    time: "2022-11-03T04:06:48Z"
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:status:
        f:conditions:
          k:{"type":"ContainersReady"}:
            .: {}
            f:lastProbeTime: {}
            f:lastTransitionTime: {}
            f:status: {}
            f:type: {}
          k:{"type":"Initialized"}:
            .: {}
            f:lastProbeTime: {}
            f:lastTransitionTime: {}
            f:status: {}
            f:type: {}
          k:{"type":"Ready"}:
            .: {}
            f:lastProbeTime: {}
            f:lastTransitionTime: {}
            f:status: {}
            f:type: {}
        f:containerStatuses: {}
        f:hostIP: {}
        f:initContainerStatuses: {}
        f:phase: {}
        f:podIP: {}
        f:podIPs:
          .: {}
          k:{"ip":"10.96.2.86"}:
            .: {}
            f:ip: {}
        f:startTime: {}
    manager: kubelet
    operation: Update
    subresource: status
    time: "2022-11-03T04:08:32Z"
  name: cd-jenkins-0
  namespace: default
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: StatefulSet
    name: cd-jenkins
    uid: 652da506-3127-4dc0-ab65-5e2a83dbdf3f
  resourceVersion: "1042605"
  uid: 5f0a6a2a-d9c5-49ff-9a6c-3b077769f384
spec:
  containers:
  - args:
    - --httpPort=8080
    env:
    - name: SECRETS
      value: /run/secrets/additional
    - name: POD_NAME
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.name
    - name: JAVA_OPTS
      value: -Dcasc.reload.token=$(POD_NAME) -Xms3500m -Xmx3500m
    - name: JENKINS_OPTS
      value: '--webroot=/var/jenkins_cache/war '
    - name: JENKINS_SLAVE_AGENT_PORT
      value: "50000"
    - name: CASC_JENKINS_CONFIG
      value: /var/jenkins_home/casc_configs
    image: jenkins/jenkins:2.361.2-jdk11
    imagePullPolicy: Always
    livenessProbe:
      failureThreshold: 5
      httpGet:
        path: /login
        port: http
        scheme: HTTP
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 5
    name: jenkins
    ports:
    - containerPort: 8080
      name: http
      protocol: TCP
    - containerPort: 50000
      name: agent-listener
      protocol: TCP
    readinessProbe:
      failureThreshold: 3
      httpGet:
        path: /login
        port: http
        scheme: HTTP
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 5
    resources:
      limits:
        cpu: "1"
        memory: 3500Mi
      requests:
        cpu: 50m
        memory: 1Gi
    securityContext:
      allowPrivilegeEscalation: false
      readOnlyRootFilesystem: true
      runAsGroup: 1000
      runAsUser: 1000
    startupProbe:
      failureThreshold: 12
      httpGet:
        path: /login
        port: http
        scheme: HTTP
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 5
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/jenkins_home
      name: jenkins-home
    - mountPath: /var/jenkins_config
      name: jenkins-config
      readOnly: true
    - mountPath: /usr/share/jenkins/ref/plugins/
      name: plugin-dir
    - mountPath: /var/jenkins_home/casc_configs
      name: sc-config-volume
    - mountPath: /run/secrets/additional
      name: jenkins-secrets
      readOnly: true
    - mountPath: /var/jenkins_cache
      name: jenkins-cache
    - mountPath: /tmp
      name: tmp-volume
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-d7t66
      readOnly: true
  - env:
    - name: POD_NAME
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.name
    - name: LABEL
      value: cd-jenkins-jenkins-config
    - name: FOLDER
      value: /var/jenkins_home/casc_configs
    - name: NAMESPACE
      value: default
    - name: REQ_URL
      value: http://localhost:8080/reload-configuration-as-code/?casc-reload-token=$(POD_NAME)
    - name: REQ_METHOD
      value: POST
    - name: REQ_RETRY_CONNECT
      value: "10"
    image: kiwigrid/k8s-sidecar:1.15.0
    imagePullPolicy: IfNotPresent
    name: config-reload
    resources: {}
    securityContext:
      allowPrivilegeEscalation: false
      readOnlyRootFilesystem: true
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/jenkins_home/casc_configs
      name: sc-config-volume
    - mountPath: /var/jenkins_home
      name: jenkins-home
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-d7t66
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  hostname: cd-jenkins-0
  initContainers:
  - command:
    - sh
    - /var/jenkins_config/apply_config.sh
    image: jenkins/jenkins:2.361.2-jdk11
    imagePullPolicy: Always
    name: init
    resources:
      limits:
        cpu: "1"
        memory: 3500Mi
      requests:
        cpu: 50m
        memory: 1Gi
    securityContext:
      allowPrivilegeEscalation: false
      readOnlyRootFilesystem: true
      runAsGroup: 1000
      runAsUser: 1000
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/jenkins_home
      name: jenkins-home
    - mountPath: /var/jenkins_config
      name: jenkins-config
    - mountPath: /usr/share/jenkins/ref/plugins
      name: plugins
    - mountPath: /var/jenkins_plugins
      name: plugin-dir
    - mountPath: /tmp
      name: tmp-volume
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-d7t66
      readOnly: true
  nodeName: gke-jenkins-cd-default-pool-f6814244-q1rw
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext:
    fsGroup: 1000
    runAsNonRoot: true
    runAsUser: 1000
  serviceAccount: cd-jenkins
  serviceAccountName: cd-jenkins
  subdomain: cd-jenkins
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - emptyDir: {}
    name: plugins
  - configMap:
      defaultMode: 420
      name: cd-jenkins
    name: jenkins-config
  - emptyDir: {}
    name: plugin-dir
  - name: jenkins-secrets
    projected:
      defaultMode: 420
      sources:
      - secret:
          items:
          - key: jenkins-admin-user
            path: chart-admin-username
          - key: jenkins-admin-password
            path: chart-admin-password
          name: cd-jenkins
  - emptyDir: {}
    name: jenkins-cache
  - name: jenkins-home
    persistentVolumeClaim:
      claimName: cd-jenkins
  - emptyDir: {}
    name: sc-config-volume
  - emptyDir: {}
    name: tmp-volume
  - name: kube-api-access-d7t66
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2022-11-03T04:07:27Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2022-11-03T04:08:32Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2022-11-03T04:08:32Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2022-11-03T04:06:48Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: containerd://a9738f9b9bba87199dc8c99f3a6d6db799d74c8856fa71411e6843de5431e581
    image: docker.io/kiwigrid/k8s-sidecar:1.15.0
    imageID: docker.io/kiwigrid/k8s-sidecar@sha256:abc3060bfe232788886f279530f8afe02614ef590ae59d9d58f637df770bcffc
    lastState: {}
    name: config-reload
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2022-11-03T04:07:27Z"
  - containerID: containerd://c27fb637a5901a26a9e3c42b23abfb8f345d7f868a7bfda3c8816f3c2529583f
    image: docker.io/jenkins/jenkins:2.361.2-jdk11
    imageID: docker.io/jenkins/jenkins@sha256:2af6730eb9fac44c27bf00a3fa668e94ebf0300b5febfee23dfa76f8954ea483
    lastState: {}
    name: jenkins
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2022-11-03T04:07:27Z"
  hostIP: 10.142.0.4
  initContainerStatuses:
  - containerID: containerd://a96d0739e2a64536176ba4bb278cd221fb0e524eb93c65504b1ca66b3f8cbcee
    image: docker.io/jenkins/jenkins:2.361.2-jdk11
    imageID: docker.io/jenkins/jenkins@sha256:2af6730eb9fac44c27bf00a3fa668e94ebf0300b5febfee23dfa76f8954ea483
    lastState: {}
    name: init
    ready: true
    restartCount: 0
    state:
      terminated:
        containerID: containerd://a96d0739e2a64536176ba4bb278cd221fb0e524eb93c65504b1ca66b3f8cbcee
        exitCode: 0
        finishedAt: "2022-11-03T04:07:24Z"
        reason: Completed
        startedAt: "2022-11-03T04:06:52Z"
  phase: Running
  podIP: 10.96.2.86
  podIPs:
  - ip: 10.96.2.86
  qosClass: Burstable
  startTime: "2022-11-03T04:06:48Z"
